# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.srcs/sources_1/bd/riscv/ip/riscv_BSCAN_0/riscv_BSCAN_0.xci
# IP: The module: 'riscv_BSCAN_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/bd_a31f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a31f || ORIG_REF_NAME==bd_a31f} -quiet] -quiet

# IP: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/ip/ip_0/bd_a31f_bs_switch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a31f_bs_switch_0 || ORIG_REF_NAME==bd_a31f_bs_switch_0} -quiet] -quiet

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/bd_a31f_ooc.xdc

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/riscv_BSCAN_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_BSCAN_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.srcs/sources_1/bd/riscv/ip/riscv_BSCAN_0/riscv_BSCAN_0.xci
# IP: The module: 'riscv_BSCAN_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/bd_a31f.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a31f || ORIG_REF_NAME==bd_a31f} -quiet] -quiet

# IP: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/ip/ip_0/bd_a31f_bs_switch_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a31f_bs_switch_0 || ORIG_REF_NAME==bd_a31f_bs_switch_0} -quiet] -quiet

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/bd_a31f_ooc.xdc

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/riscv_BSCAN_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_BSCAN_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
