# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/ip/ip_0/constraints/bs_switch.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_a31f_bs_switch_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/ip/ip_0/bd_a31f_bs_switch_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_a31f_bs_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/ip/ip_0/constraints/bs_switch.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_a31f_bs_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/ip/riscv_BSCAN_0/bd_0/ip/ip_0/bd_a31f_bs_switch_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_a31f_bs_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
