# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/constraints/top.xdc

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/constraints/sdc.xdc

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/constraints/uart.xdc

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/constraints/ddr.xdc

# Block Designs: bd/riscv/riscv.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv || ORIG_REF_NAME==riscv} -quiet] -quiet

# IP: bd/riscv/ip/riscv_BSCAN_0/riscv_BSCAN_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_BSCAN_0 || ORIG_REF_NAME==riscv_BSCAN_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_smc_1_0/riscv_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_axi_smc_1_0 || ORIG_REF_NAME==riscv_axi_smc_1_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_mem_reset_control_0_0/riscv_mem_reset_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_mem_reset_control_0_0 || ORIG_REF_NAME==riscv_mem_reset_control_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_mig_7series_0_0 || ORIG_REF_NAME==riscv_mig_7series_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_SD_0/riscv_SD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_SD_0 || ORIG_REF_NAME==riscv_SD_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_UART_0/riscv_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_UART_0 || ORIG_REF_NAME==riscv_UART_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_quad_spi_0_0/riscv_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_axi_quad_spi_0_0 || ORIG_REF_NAME==riscv_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_io_axi_m_0/riscv_io_axi_m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_io_axi_m_0 || ORIG_REF_NAME==riscv_io_axi_m_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_io_axi_s_0/riscv_io_axi_s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_io_axi_s_0 || ORIG_REF_NAME==riscv_io_axi_s_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_xlconcat_0_0/riscv_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_xlconcat_0_0 || ORIG_REF_NAME==riscv_xlconcat_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_JTAG_0/riscv_JTAG_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_JTAG_0 || ORIG_REF_NAME==riscv_JTAG_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_RocketChip_0 || ORIG_REF_NAME==riscv_RocketChip_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_clk_wiz_0_0 || ORIG_REF_NAME==riscv_clk_wiz_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_util_vector_logic_0_0/riscv_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_util_vector_logic_0_0 || ORIG_REF_NAME==riscv_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/imocanu/Public/Vivado_proj/for_RISCV/riscv-ml/vivado_proj/riscv-ml/riscv-ml.gen/sources_1/bd/riscv/riscv_ooc.xdc
